version: "3"
services:
  database:
    image: mysql:${VERSION_MYSQL}
    container_name: ${HOST_MYSQL}
    ports:
      - ${DOCKER_PORT_MYSQL}:${DOCKER_PORT_MYSQL}
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

#  clothes-backend:
#    image: clothes-backend
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#  delivery-platform:
#    image: delivery-platform
#    build: ../delivery-platform/
#    ports:
#      - "8081:8081"
#    depends_on:
#      - database
#  clothes-frontend:
#    image: clothes-frontend
#    build: ../clothes-frontend/
#    ports:
#      - "80:80"